.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\" Portions extracted from linux/mm/swap.c:
.\"                Copyright (C) 1991, 1992  Linus Torvalds
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified 21 Aug 1994 by Michael Chastain <mec@shell.portal.com>:
.\"   Added text about calling restriction (new in kernel 1.1.20 I believe).
.\"   N.B. calling "idle" from user process used to hang process!
.\" Modified Thu Oct 31 14:41:15 1996 by Eric S. Raymond <esr@thyrsus.com>
.\"
.\" Дата последней коррекции перевода 08.12.2003
.\" Перевод с английского сделал Виктор Вислобоков <corochoone@perm.ru>
.\" http://www.linuxshare.ru/projects/trans/mans.html
.\"
.TH IDLE 2 1994-08-21 "Linux 1.1.46" "Linux Programmer's Manual"
.SH ИМЯ
idle \- делает процесс 0 простаиваемым
.SH ОБЗОР
.B #include <unistd.h>
.sp
.B int idle(void);
.SH ОПИСАНИЕ
.B idle
\- это внутрениий системный вызов, используемый во время начальной
загрузки. Он помечает страницы процесса как выгружаемые на своппинг,
снижает его приоритет и входит в главную петлю планировщика.
.B idle
никогда не возвращает управление.
.PP
Только процесс 0 может вызывать
.BR idle .
Все пользовательские процессы, даже процессы с правами суперпользователя,
будут получать
.BR EPERM .
.SH "ВОЗВРАЩАЕМОЕ ЗНАЧЕНИЕ"
.B idle
никогда не возвращает в процесс 0 и всегда возвращает \-1 для
пользовательских процессов.
.SH ОШИБКИ
.TP
.B EPERM
Всегда для пользовательских процессов.
.SH "СООТВЕТСТВИЕ СТАНДАРТАМ"
Данная функция специфична для Linux и не должна использоваться в
программах, которые задуманы как переносимые.
.SH ЗАМЕЧАНИЯ
Начиная с 2.3.13 этот системный вызов нигде не существует.
.SH ПЕРЕВОД
Перевёл с английского Виктор Вислобоков <corochoone@perm.ru> 2003
