.\" Hey Emacs! This file is -*- nroff -*- source.
.\" This page is in the public domain.
.\"
.\" Дата последней коррекции перевода 11.12.2003
.\" Перевод с английского сделал Виктор Вислобоков <corochoone@perm.ru>
.\" http://www.linuxshare.ru/projects/man/
.\"
.TH UNIMPLEMENTED 2 2003-02-01 "Linux 2.4.20" "Руководство программиста Linux"
.SH ИМЯ
exit_group,
madvise1,
rt_sigaction,
rt_sigpending,
rt_sigprocmask,
rt_sigqueueinfo,
rt_sigreturn,
rt_sigsuspend,
rt_sigtimedwait,
ugetrlimit
\- недокументированные системные вызовы
.SH ОБЗОР
Недокументированные системные вызовы.
.SH ОПИСАНИЕ
Ядро 2.4.20 имеет 253 системных вызова для архитектуры i386.
Вышеперечисленные пока не были документированы.
.SH "СМОТРИТЕ ТАКЖЕ"
.BR obsolete (2),
.BR syscalls (2),
.BR unimplemented (2)
.SH ПЕРЕВОД
Перевёл с английского Виктор Вислобоков <corochoone@perm.ru> 2003
