.\" Copyright (c) 1993 Michael Haardt (michael@moria.de), Fri Apr  2 11:32:09 MET DST 1993
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" Modified Sun Jul 25 11:06:34 1993 by Rik Faith (faith@cs.unc.edu)
.\" Corrected Mon Oct 21 17:47:19 EDT 1996 by Eric S. Raymond (esr@thyrsus.com)
.\"
.\" Дата последней коррекции перевода 08.03.2004
.\" Перевод с английского сделал Виктор Вислобоков <corochoone@perm.ru>
.\" http://www.linuxshare.ru/projects/man/
.\"
.TH NOLOGIN 5 1992-12-29 1992" "Linux" "Руководство программиста Linux"
.SH ИМЯ
nologin \- предотвращает вход в систему пользователей, отличных от root
.SH ОПИСАНИЕ
Если существует файл \fB/etc/nologin\fP, то
.BR login (1)
будет разрешать доступ в систему только пользователю root.  Остальным
пользователям будет показано содержимое этого файла, а в доступе в
систему будет отказано.
.SH ФАЙЛЫ
/etc/nologin
.SH "СМОТРИ ТАКЖЕ"
.BR login (1),
.BR shutdown (8)
.SH ПЕРЕВОД
Перевёл с английского Виктор Вислобоков <corochoone@perm.ru> 2004
