.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sun Jul 25 10:40:44 1993 by Rik Faith (faith@cs.unc.edu)
.TH STRCOLL 3  "12 апреля 1993" "GNU" "Руководство программиста"
.SH НАЗВАНИЕ
strcoll \- сравнение двух строк с учетом региональных настроек
.SH СИНТАКСИС
.nf
.B #include <string.h>
.sp
.BI "int strcoll(const char *" s1 ", const char *" s2 );
.fi
.SH ОПИСАНИЕ
Функция \fBstrcoll()\fP сравнивает две строки \fIs1\fP и \fIs2\fP.
Она возвращает целое число, меньшее, равное, или больше нуля, если 
\fIs1\fP, соответственно, меньше, равна, или больше чем \fIs2\fP.
Сравнение строк производится в соответствии с категорией
\fILC_COLLATE\fP текущих региональных настроек программы.  (Смотри
\fBsetlocale\fP(3)).
.SH "ВОЗВРАЩАЕМОЕ ЗНАЧЕНИЕ"
Функция \fBstrcoll()\fP возвращает целое число, меньшее, равное, или больше
нуля, если строка \fIs1\fP, соответственно, меньше, равна, или больше
чем \fIs2\fP, если при этом обе они интерпретируются в соответствии с
текущими региональными настройками.
.SH СООТВЕТСТВИЕ СТАНДАРТАМ
SVID 3, BSD 4.3, ISO 9899
.SH ЗАМЕЧАНИЯ
При установке locale в \fI"POSIX"\fP или \fI"C"\fP \fBstrcoll()\fP
эквивалентна \fBstrcmp()\fP.
.SH "СМОТРИ ТАКЖЕ"
.BR bcmp "(3), " memcmp "(3), " strcasecmp "(3), " strcmp (3),
.BR strxfrm "(3), " setlocale (3)
.SH ПЕРЕВОД
.nf
Перевод с английского (C) 2000 Дмитрий Морожников 
    (dm@simplex.irkutsk.ru, 2:5070/141.3)
.fi
