.TH TZSELECT 8
.SH ИМЯ
tzselect \- выбор часового пояса
.SH ОБЗОР
.B tzselect
.SH ОПИСАНИЕ
Программа
.B tzselect
выясняет у пользователя его текущее местоположение и выводит
описание часового пояса на устройство стандартного вывода.
Это описание можно использовать в качестве значения переменной
окружения TZ.
.PP
Общение с пользователем происходит через устройства стандартного ввода
и стандартных ошибок. 
.SH "ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ"
.TP
\fBAWK\fP
Имя POSIX-совместимого интерпретатора языка
.I awk
(по умолчанию:
.BR awk ).
.TP
\fBTZDIR\fP
Имя каталога, содержащего файлы с описаниями часовых поясов
(по умолчанию: 
.IR /usr/local/etc/zoneinfo ).
.SH ФАЙЛЫ
.TP
\fBTZDIR\fP\fI/iso3166.tab\fP
Таблица двухсимвольных кодов стран и их названий, согласно 
стандарту ISO 3166.
.TP
\fBTZDIR\fP\fI/zone.tab\fP
Таблица кодов стран, широты и долготы, значений переменной TZ и описаний.
.TP
\fBTZDIR\fP\fI/\fP\fITZ\fP
Файл, содержащий описание часового пояса \fITZ\fP.
.SH "ВОЗВРАЩАЕМОЕ ЗНАЧЕНИЕ"
Возвращаемое значение равно нулю, если пользователь правильно ввел 
информацию о часовом поясе, в противном случае возвращаемое значение
больше нуля.
.SH "СМОТРИ ТАКЖЕ"
.BR newctime (3),
.BR tzfile (5),
.BR zdump (8),
.BR zic (8)
.RE
.SH ПЕРЕВОД
Перевел с английского Алексей Миллер <asm@asm.kiev.ua> 2000
