.TH ZDUMP 8
.SH ИМЯ
zdump \- информация о часовом поясе
.SH ОБЗОР
.B zdump
[
.B \-v
] [
.B \-c
год ] [ пояс ... ]
.SH ОПИСАНИЕ
.I Zdump
распечатывает текущее время для каждого
.IR "часового пояса" ,
указанного в командной строке.
.PP
Доступны следующие параметры:
.TP
.B \-v
Для каждого
.IR "часового пояса" ,
указанного в командной строке, печатается наименьшее возможное время,
время через день после наименьшего возможного времени, время за одну
секунду до
и точное время обнаруженных временных разрывов, время за день до максимально 
возможного времени, и максимально возможное время.
Каждая строка заканчивается
.BR isdst=1 ,
если указанное время является летним временем (Daylight Saving Time), или
.B isdst=0
-- если нет.
.TP
.BI "\-c " год
Обрезать подробный отчет в районе начала указанного года.
.SH "СМОТРИ ТАКЖЕ"
newctime(3), tzfile(5), zic(8)
.RE
.SH ПЕРЕВОД
Перевел с английского Алексей Миллер <asm@asm.kiev.ua> 2000
